/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.multixsoft.hospitapp.gui;

import com.multixsoft.hospitapp.entities.Doctor;
import java.awt.Dimension;
import java.awt.GraphicsConfiguration;
import java.awt.Insets;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Vane
 */
public class Frame_Doctor extends javax.swing.JFrame {

    /**
     * Creates new form GUIDoctorHospitApp
     */
    public JIF_ProximasCitas proximasCitas;
    public JIF_VerCItas verCitas;
    private static Doctor doctor;

    public Frame_Doctor() {
        initComponents();
//        this.setResizable(false);
        //this is to make the window the maximum size
        GraphicsConfiguration gc = getGraphicsConfiguration();
        Rectangle screenRect = gc.getBounds();
        System.out.println("Screen size: " + screenRect);

        Toolkit tk = Toolkit.getDefaultToolkit();
        Insets desktopInsets = tk.getScreenInsets(gc);
        System.out.println("OS Insets: " + desktopInsets);

        Insets frameInsets = getInsets();     // only works after a pack() call
        System.out.println("JFrame Insets: " + frameInsets);

        Dimension tfDim = this.getPreferredSize();   // size of text field
        System.out.println("Box TF Size: " + tfDim);
        System.out.println("Time TF Size: " + this.getPreferredSize());

        int pWidth = screenRect.width - (desktopInsets.left + desktopInsets.right)
                - (frameInsets.left + frameInsets.right);

        int pHeight = screenRect.height - (desktopInsets.top + desktopInsets.bottom)
                - (frameInsets.top + frameInsets.bottom);
        System.out.println("dimensions width=" + pWidth + " hieght=" + pHeight);
//        this.setPreferredSize(new Dimension(pWidth, pHeight));
        this.setSize(pWidth, pHeight);

        //center the frame in the center of the screen
        Toolkit aKit = this.getToolkit();
        Dimension windowSize = aKit.getScreenSize();
        this.setBounds((windowSize.width / 2) - (this.getWidth() / 2),
                (windowSize.height / 2) - (this.getHeight() / 2),
                this.getWidth(), this.getHeight());
        
        jDesktopPane1.setBorder(new BorderBackImage());
           
        Calendar cal = Calendar.getInstance();
        jLabelTiempo.setText(cal.getTime().toString());
    }

    public Frame_Doctor(Doctor d) {
        this();
        doctor = d;

        this.setTitle("Escritorio del Médico " + doctor.getFirstName() + " " + doctor.getLastName());

        jLabelDoctorName.setText(d.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBarPacientes = new javax.swing.JToolBar();
        jButtonVerCitas = new javax.swing.JButton();
        jButtonProximasCitas = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelDoctorName = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelTiempo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jToolBarPacientes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBarPacientes.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBarPacientes.setRollover(true);

        jButtonVerCitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/multixsoft/hospitapp/resources/icon-people4.png"))); // NOI18N
        jButtonVerCitas.setText("          Ver Citas           ");
        jButtonVerCitas.setFocusable(false);
        jButtonVerCitas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonVerCitas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonVerCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerCitasActionPerformed(evt);
            }
        });
        jToolBarPacientes.add(jButtonVerCitas);

        jButtonProximasCitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/multixsoft/hospitapp/resources/icon-write.png"))); // NOI18N
        jButtonProximasCitas.setText("  Citas Programadas ");
        jButtonProximasCitas.setFocusable(false);
        jButtonProximasCitas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonProximasCitas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonProximasCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximasCitasActionPerformed(evt);
            }
        });
        jToolBarPacientes.add(jButtonProximasCitas);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 842, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBarPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBarPacientes, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                    .addComponent(jDesktopPane1))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/multixsoft/hospitapp/imagenes/icon-person.png"))); // NOI18N

        jLabel2.setText("Logged In como Médico:");

        jLabelDoctorName.setText("jLabel3");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/multixsoft/hospitapp/imagenes/icon-finish.png"))); // NOI18N
        jButton1.setText("Log Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelTiempo.setText("jLabel4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelDoctorName))
                    .addComponent(jLabelTiempo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel2)
                    .addComponent(jLabelDoctorName))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTiempo)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVerCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerCitasActionPerformed
        verCitas = new JIF_VerCItas(doctor);
        jDesktopPane1.add(verCitas);
        
        verCitas.show();
        verCitas.moveToFront();
    }//GEN-LAST:event_jButtonVerCitasActionPerformed

    private void jButtonProximasCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximasCitasActionPerformed
        proximasCitas = new JIF_ProximasCitas(doctor);
        jDesktopPane1.add(proximasCitas);
        
        proximasCitas.show();
        proximasCitas.moveToFront();
    }//GEN-LAST:event_jButtonProximasCitasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        showConfirmacion();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Mac OS X".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
//                if ("Metal".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Frame_Doctor().setVisible(true);
            }
        });
    }
    
    public void showConfirmacion() {
        int n = JOptionPane.showConfirmDialog(
                null, "Esta seguro de salir?", "Confirmación",
                JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else if (n == JOptionPane.NO_OPTION) {
            //JOptionPane.showMessageDialog(null, "Continueando...");
        } else {
            //JOptionPane.showMessageDialog(null, "Continueando...");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonProximasCitas;
    private javax.swing.JButton jButtonVerCitas;
    public static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDoctorName;
    private javax.swing.JLabel jLabelTiempo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBarPacientes;
    // End of variables declaration//GEN-END:variables
}
