/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.multixsoft.hospitapp.gui;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.awt.GraphicsConfiguration;
import java.awt.Insets;
import java.awt.Rectangle;
import java.util.Calendar;
import javax.swing.JInternalFrame;

/**
 *
 * @author manuelmartinez
 */
public class Frame_Administrador extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public Frame_Administrador() {
        initComponents();

        //this is to make the window the maximum size
        GraphicsConfiguration gc = getGraphicsConfiguration();
        Rectangle screenRect = gc.getBounds();
        System.out.println("Screen size: " + screenRect);

        Toolkit tk = Toolkit.getDefaultToolkit();
        Insets desktopInsets = tk.getScreenInsets(gc);
        System.out.println("OS Insets: " + desktopInsets);

        Insets frameInsets = getInsets();     // only works after a pack() call
        System.out.println("JFrame Insets: " + frameInsets);

        Dimension tfDim = this.getPreferredSize();   // size of text field
        System.out.println("Box TF Size: " + tfDim);
        System.out.println("Time TF Size: " + this.getPreferredSize());

        int pWidth = screenRect.width - (desktopInsets.left + desktopInsets.right)
                - (frameInsets.left + frameInsets.right);

        int pHeight = screenRect.height - (desktopInsets.top + desktopInsets.bottom)
                - (frameInsets.top + frameInsets.bottom);
        System.out.println("dimensions width=" + pWidth + " hieght=" + pHeight);
//        this.setPreferredSize(new Dimension(pWidth, pHeight));
        this.setSize(pWidth, pHeight);

        //center the frame in the center of the screen
        Toolkit aKit = this.getToolkit();
        Dimension windowSize = aKit.getScreenSize();
        this.setBounds((windowSize.width / 2) - (this.getWidth() / 2),
                (windowSize.height / 2) - (this.getHeight() / 2),
                this.getWidth(), this.getHeight());

        //poner la imagen al destop pane
        jDesktopPanePacientes.setBorder(new BorderBackImage());
        jDesktopPaneDoctores.setBorder(new BorderBackImage());
        jDesktopPaneCitas.setBorder(new BorderBackImage());

//        BorderBackImage bb= new BorderBackImage();
//        bb.rescale();
//        jPanel2.setBorder(bb);
        Calendar cal = Calendar.getInstance();
        jLabelTime.setText(cal.getTime().toString());

        this.setIconImage(Toolkit.getDefaultToolkit().getImage("res/icon.png"));
//        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldPassword = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelTime = new javax.swing.JLabel();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelPacientes = new javax.swing.JPanel();
        jToolBarPacientes = new javax.swing.JToolBar();
        jButtonVerPaciente = new javax.swing.JButton();
        jButtonAsignarPaciente = new javax.swing.JButton();
        jDesktopPanePacientes = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonVerDoctores = new javax.swing.JButton();
        jButtonCancelarCita = new javax.swing.JButton();
        jDesktopPaneDoctores = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        jButtonAgendarCita = new javax.swing.JButton();
        jButtonAdministrarCitas = new javax.swing.JButton();
        jDesktopPaneCitas = new javax.swing.JDesktopPane();

        jPasswordField2.setText("jPasswordField2");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/multixsoft/hospitapp/imagenes/icon-person.png"))); // NOI18N

        jLabel2.setText("Logged In:");

        jLabel3.setText("Admin");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/multixsoft/hospitapp/imagenes/icon-finish.png"))); // NOI18N
        jButton1.setText("Log Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelTime.setText("Tiempo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addComponent(jLabelTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelTime)
                            .addComponent(jLabel1))))
                .addContainerGap())
        );

        jTabbedPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jToolBarPacientes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBarPacientes.setFloatable(false);
        jToolBarPacientes.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBarPacientes.setRollover(true);
        jToolBarPacientes.setBorderPainted(false);

        jButtonVerPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/multixsoft/hospitapp/imagenes/icon-people.png"))); // NOI18N
        jButtonVerPaciente.setText("   Ver Pacientes   ");
        jButtonVerPaciente.setFocusable(false);
        jButtonVerPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonVerPaciente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonVerPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerPacienteActionPerformed(evt);
            }
        });
        jToolBarPacientes.add(jButtonVerPaciente);

        jButtonAsignarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/multixsoft/hospitapp/imagenes/icon-people4.png"))); // NOI18N
        jButtonAsignarPaciente.setText("Asignar Paciente");
        jButtonAsignarPaciente.setFocusable(false);
        jButtonAsignarPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAsignarPaciente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAsignarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAsignarPacienteActionPerformed(evt);
            }
        });
        jToolBarPacientes.add(jButtonAsignarPaciente);

        jDesktopPanePacientes.setLayout(null);

        javax.swing.GroupLayout jPanelPacientesLayout = new javax.swing.GroupLayout(jPanelPacientes);
        jPanelPacientes.setLayout(jPanelPacientesLayout);
        jPanelPacientesLayout.setHorizontalGroup(
            jPanelPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPacientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBarPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPanePacientes))
        );
        jPanelPacientesLayout.setVerticalGroup(
            jPanelPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanePacientes)
            .addComponent(jToolBarPacientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Pacientes", jPanelPacientes);

        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        jButtonVerDoctores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/multixsoft/hospitapp/imagenes/icon-people.png"))); // NOI18N
        jButtonVerDoctores.setText("   Ver Doctores  ");
        jButtonVerDoctores.setFocusable(false);
        jButtonVerDoctores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonVerDoctores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonVerDoctores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerDoctoresActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonVerDoctores);

        jButtonCancelarCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/multixsoft/hospitapp/imagenes/icon-write.png"))); // NOI18N
        jButtonCancelarCita.setText("      Ver Citas      ");
        jButtonCancelarCita.setFocusable(false);
        jButtonCancelarCita.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCancelarCita.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCancelarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarCitaActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonCancelarCita);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPaneDoctores))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jDesktopPaneDoctores)
        );

        jTabbedPane.addTab("Doctores", jPanel1);

        jToolBar2.setFloatable(false);
        jToolBar2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar2.setRollover(true);

        jButtonAgendarCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/multixsoft/hospitapp/imagenes/icon-calendar.png"))); // NOI18N
        jButtonAgendarCita.setText("   Agendar Cita   ");
        jButtonAgendarCita.setFocusable(false);
        jButtonAgendarCita.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAgendarCita.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAgendarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendarCitaActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonAgendarCita);

        jButtonAdministrarCitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/multixsoft/hospitapp/imagenes/icon-clipboard.png"))); // NOI18N
        jButtonAdministrarCitas.setText("Administra Cita ");
        jButtonAdministrarCitas.setFocusable(false);
        jButtonAdministrarCitas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAdministrarCitas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAdministrarCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdministrarCitasActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonAdministrarCitas);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPaneCitas))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPaneCitas)
        );

        jTabbedPane.addTab("Citas", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        showConfirmacion();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonAdministrarCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdministrarCitasActionPerformed
        JInternalFrame[] allFrames = jDesktopPaneCitas.getAllFrames();
        for (int i = 0; i < allFrames.length; i++) {
            JInternalFrame frame = allFrames[i];
            String name = frame.getName();
            if (name.equalsIgnoreCase("abccita")) {
                frame.moveToFront();
                return;
            }
        }
        JIF_ABC_Cita cita_frame = new JIF_ABC_Cita(null, jDesktopPaneCitas);
        cita_frame.setName("abccita");
        cita_frame.setVisible(true);
        jDesktopPaneCitas.add(cita_frame);
        cita_frame.requestFocusInWindow();
        cita_frame.moveToFront();
    }//GEN-LAST:event_jButtonAdministrarCitasActionPerformed

    private void jButtonAgendarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendarCitaActionPerformed
        JInternalFrame[] allFrames = jDesktopPaneCitas.getAllFrames();
        for (int i = 0; i < allFrames.length; i++) {
            JInternalFrame frame = allFrames[i];
            String name = frame.getName();
            if (name.equalsIgnoreCase("agendarcita")) {
                frame.moveToFront();
                return;
            }
        }
        JIF_AgendarCita cita_frame = new JIF_AgendarCita();
        cita_frame.setName("agendarcita");
        cita_frame.setVisible(true);
        jDesktopPaneCitas.add(cita_frame);
        cita_frame.requestFocusInWindow();
        cita_frame.moveToFront();
    }//GEN-LAST:event_jButtonAgendarCitaActionPerformed

    private void jButtonCancelarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarCitaActionPerformed
        JInternalFrame[] allFrames = jDesktopPaneDoctores.getAllFrames();
        for (int i = 0; i < allFrames.length; i++) {
            JInternalFrame allFrame = allFrames[i];
            String name = allFrame.getName();
            if (name != null) {
                if (name.equalsIgnoreCase("cancelcita")) {
                    allFrame.moveToFront();
                    return;
                }
            }
        }

        JIF_CancelarCita cancelCitaFrame = new JIF_CancelarCita();
        cancelCitaFrame.setName("cancelcita");
        cancelCitaFrame.setVisible(true);
        jDesktopPaneDoctores.add(cancelCitaFrame);
        cancelCitaFrame.requestFocusInWindow();
        cancelCitaFrame.moveToFront();
    }//GEN-LAST:event_jButtonCancelarCitaActionPerformed

    private void jButtonVerDoctoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerDoctoresActionPerformed
        JInternalFrame[] allFrames = jDesktopPaneDoctores.getAllFrames();
        for (int i = 0; i < allFrames.length; i++) {
            JInternalFrame frame = allFrames[i];
            String name = frame.getName();
            if (name != null) {
                if (name.equalsIgnoreCase("verdoctor")) {
                    frame.moveToFront();
                    return;
                }
            }
        }
        JIF_Doctores doc_frame = new JIF_Doctores(jDesktopPaneDoctores);
        doc_frame.setName("verdoctor");
        doc_frame.setVisible(true);
        jDesktopPaneDoctores.add(doc_frame);
        doc_frame.requestFocusInWindow();
        doc_frame.moveToFront();
    }//GEN-LAST:event_jButtonVerDoctoresActionPerformed

    private void jButtonAsignarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAsignarPacienteActionPerformed
        JInternalFrame[] allFrames = jDesktopPanePacientes.getAllFrames();
        for (int i = 0; i < allFrames.length; i++) {
            JInternalFrame allFrame = allFrames[i];
            String name = allFrame.getName();
            if (name.equalsIgnoreCase("assignar")) {
                allFrame.moveToFront();
                return;
            }
        }

        JIF_AsignarPaciente asignar
                = new JIF_AsignarPaciente();
        asignar.setName("assignar");
        asignar.setVisible(true);
        jDesktopPanePacientes.add(asignar);
        asignar.requestFocusInWindow();

        asignar.moveToFront();
    }//GEN-LAST:event_jButtonAsignarPacienteActionPerformed

    private void jButtonVerPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerPacienteActionPerformed
        JInternalFrame[] allFrames = jDesktopPanePacientes.getAllFrames();
        for (int i = 0; i < allFrames.length; i++) {
            JInternalFrame allFrame = allFrames[i];
            String name = allFrame.getName();
            if (name.equalsIgnoreCase("verpaciente")) {
                allFrame.moveToFront();
                return;
            }
        }
        JIF_Pacientes verPatientFrame
                = new JIF_Pacientes();
        verPatientFrame.setName("verpaciente");
        verPatientFrame.setVisible(true);
        jDesktopPanePacientes.add(verPatientFrame);
        verPatientFrame.requestFocusInWindow();
        verPatientFrame.moveToFront();
    }//GEN-LAST:event_jButtonVerPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Mac OS X".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }

            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(Frame_LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Frame_Administrador().setVisible(true);
            }
        });
    }

    public void showConfirmacion() {
        int n = JOptionPane.showConfirmDialog(
                null, "Esta seguro de salir?", "Confirmación",
                JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else if (n == JOptionPane.NO_OPTION) {
            //JOptionPane.showMessageDialog(null, "Continueando...");
        } else {
            //JOptionPane.showMessageDialog(null, "Continueando...");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAdministrarCitas;
    private javax.swing.JButton jButtonAgendarCita;
    private javax.swing.JButton jButtonAsignarPaciente;
    private javax.swing.JButton jButtonCancelarCita;
    private javax.swing.JButton jButtonVerDoctores;
    private javax.swing.JButton jButtonVerPaciente;
    private javax.swing.JDesktopPane jDesktopPaneCitas;
    private javax.swing.JDesktopPane jDesktopPaneDoctores;
    private javax.swing.JDesktopPane jDesktopPanePacientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelTime;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelPacientes;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextField jTextFieldPassword;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBarPacientes;
    // End of variables declaration//GEN-END:variables
}
