/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.multixsoft.hospitapp.gui;

import com.multixsoft.hospitapp.connector.ConectorPatientDataRecorder;
import com.multixsoft.hospitapp.entities.Appointment;
import com.multixsoft.hospitapp.entities.Report;
import com.multixsoft.hospitapp.utilities.JPanes;
import com.multixsoft.hospitapp.utilities.ReportGenerator;
import java.awt.FileDialog;
import java.awt.Frame;
import javax.swing.JFrame;

/**
 *
 * @author manuelmartinez
 */
public class JIF_Reportes extends javax.swing.JInternalFrame {

    private Report report;
    private Appointment cita;
    private long idReportPlusOne;

    /**
     * Creates new form JIF_Reportes
     * @param cita
     */
    public JIF_Reportes(Appointment cita) {
        initComponents();

        this.cita = cita;
        
        this.setName("reportes");
        this.setTitle("Reporte de la Cita: "+cita.toString());
        
//        jButtonCrear.setEnabled(true);
//        jButtonPDF.setEnabled(false);
        jButtonCrear.setVisible(false);
        
         idReportPlusOne = ConectorPatientDataRecorder.getInstance().getIdReportPlusOne();
        jTextFieldReportID.setText(idReportPlusOne+"");
    }

    public JIF_Reportes(Report r, Appointment cita) {
        this(cita);
        report = r;

        jTextFieldReportID.setText(r.getIdReport() + "");
        jTextAreaDescripcion.setText(r.getDescription());
        jTextFieldMedicina.setText(r.getMedicine());
        jTextAreaIndicaciones.setText(r.getMedicine());

        jButtonCrear.setEnabled(false);
        jButtonPDF.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonCrear = new javax.swing.JButton();
        jButtonPDF = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldReportID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDescripcion = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMedicina = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaIndicaciones = new javax.swing.JTextArea();
        jLabelErrorMsg = new javax.swing.JLabel();
        jLabelErrorMed = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButtonCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/multixsoft/hospitapp/imagenes/ic_create.png"))); // NOI18N
        jButtonCrear.setText("Crear");
        jButtonCrear.setEnabled(false);
        jButtonCrear.setFocusable(false);
        jButtonCrear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCrear.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonCrear);

        jButtonPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/multixsoft/hospitapp/imagenes/ic_flag_green.png"))); // NOI18N
        jButtonPDF.setText("PDF de Reporte");
        jButtonPDF.setFocusable(false);
        jButtonPDF.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPDF.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPDFActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonPDF);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Reporte"));

        jLabel1.setText("ID Reporte:");

        jTextFieldReportID.setEditable(false);

        jLabel2.setText("Descripcion:");

        jTextAreaDescripcion.setColumns(20);
        jTextAreaDescripcion.setRows(5);
        jScrollPane2.setViewportView(jTextAreaDescripcion);

        jLabel3.setText("Medicina:");

        jTextFieldMedicina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMedicinaActionPerformed(evt);
            }
        });

        jLabel4.setText("Indicaciones:");

        jTextAreaIndicaciones.setColumns(20);
        jTextAreaIndicaciones.setRows(5);
        jScrollPane3.setViewportView(jTextAreaIndicaciones);

        jLabelErrorMsg.setText("   ");

        jLabelErrorMed.setText("   ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jTextFieldMedicina)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelErrorMsg)
                            .addComponent(jLabelErrorMed))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextFieldReportID))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldReportID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelErrorMsg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldMedicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelErrorMed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMedicinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMedicinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMedicinaActionPerformed

    private void jButtonPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPDFActionPerformed
        String descripcion = jTextAreaDescripcion.getText();
        String medicina = jTextFieldMedicina.getText();
        String indicaciones = jTextAreaIndicaciones.getText();
        
        System.err.println("Debug Cita en JIFRepo:"+cita.getDate().toString());
        
        report = new Report(idReportPlusOne);
        report.setDescription(descripcion);
        report.setMedicine(medicina);
        report.setIndications(indicaciones);
        report.setIdAppointment(cita);
        report.setPatientNss(cita.getPatientNss());
        
        
        JFrame f = null;
        FileDialog dialogo = new FileDialog(f,
                "Save?",
                FileDialog.SAVE);
        dialogo.setFile(cita.getPatientNss().getFirstName()+"_"+cita.getIdAppointment()+".pdf"); //Filtro de archivos
        dialogo.setDirectory("."); //Directorio actual
        dialogo.setVisible(true); //Muestra el cuadro de dialogo
        String directory = dialogo.getDirectory();//Obtenemos el directorio
        String filename = dialogo.getFile();//Obtenemos es nombre del archivo seleccionado
        if (directory != null && filename != null) {

            ReportGenerator gen = new ReportGenerator(directory + filename);
            boolean createReport = gen.createReport(report);
            if (createReport) {
                JPanes.getInstance().msgPane("El PDF se generó con éxito!");
            } else {
                JPanes.getInstance().errorPane("No se pudo generar el PDF.");
            }
            
        }


    }//GEN-LAST:event_jButtonPDFActionPerformed

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        String descripcion = jTextAreaDescripcion.getText();
        String medicina = jTextFieldMedicina.getText();
        String indicaciones = jTextAreaIndicaciones.getText();
        
        System.err.println("Debug Cita en JIFRepo:"+cita.getDate().toString());
        
        report = new Report(idReportPlusOne);
        report.setDescription(descripcion);
        report.setMedicine(medicina);
        report.setIndications(indicaciones);
        report.setIdAppointment(cita);
        report.setPatientNss(cita.getPatientNss());
        
        ConectorPatientDataRecorder pdr = ConectorPatientDataRecorder.getInstance();
        boolean saved = pdr.saveHistoryAppointment(report);
        
        if(saved){
            JPanes.getInstance().msgPane("Se almaceno el Reporte con éxito.");
            jButtonPDF.setEnabled(true);
        }else{
            JPanes.getInstance().errorPane("Hubo un error al almacenar el reporte.");
        }
        jButtonCrear.setEnabled(false);
        
    }//GEN-LAST:event_jButtonCrearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JButton jButtonPDF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelErrorMed;
    private javax.swing.JLabel jLabelErrorMsg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaDescripcion;
    private javax.swing.JTextArea jTextAreaIndicaciones;
    private javax.swing.JTextField jTextFieldMedicina;
    private javax.swing.JTextField jTextFieldReportID;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
