/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.multixsoft.hospitapp.gui;

import com.multixsoft.hospitapp.connector.ConectorServicio;
import com.multixsoft.hospitapp.entities.Patient;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import com.multixsoft.hospitapp.connector.ConectorPatientManager;
import com.multixsoft.hospitapp.entities.Doctor;
import com.multixsoft.hospitapp.utilities.FixedSizeAlphaNumericDocument;
import com.multixsoft.hospitapp.utilities.FixedSizeAlphabeticalDocument;
import com.multixsoft.hospitapp.utilities.FixedSizeEmailDocument;
import com.multixsoft.hospitapp.utilities.FixedSizeNumberDocument;
import com.multixsoft.hospitapp.utilities.Validator;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author manuelmartinez
 */
public class VerPacientesJInternalFrame extends javax.swing.JInternalFrame {

    private Patient selectedPatient;

    /**
     * Creates new form VerPacientesJInternalFrame
     */
    public VerPacientesJInternalFrame() {
        initComponents();
        this.setResizable(false);

        jButtonEliminarPaciente.setEnabled(false);
        jButtonModificarPaciente.setEnabled(false);

        jTextFieldNombre.setDocument(new FixedSizeAlphabeticalDocument(jTextFieldNombre, 100));
        jTextFieldApellido.setDocument(new FixedSizeAlphabeticalDocument(jTextFieldApellido, 100));

        jTextFieldNSS.setDocument(new FixedSizeNumberDocument(jTextFieldNSS, 11));
        jPasswordField1.setDocument(new FixedSizeAlphaNumericDocument(jPasswordField1, 64));

        jTextFieldEmail.setDocument(new FixedSizeEmailDocument(jTextFieldEmail, 64));

        //Lista de pacientes
        actualizarListaPacientes();

    }

    private void actualizarListaPacientes() {
        //Lista de pacientes
        ConectorServicio servidor = ConectorServicio.getInstance();
        jListPacientes.addListSelectionListener(new ManejadorListaPacientes());
        List<Patient> pacientes = servidor.obtenerListaPatient();
        DefaultListModel modelo = new DefaultListModel();
        for (Patient c : pacientes) {
            modelo.addElement(c);
        }
        jListPacientes.setModel(modelo);
    }

    public void limpiarCampos() {

        jTextFieldNSS.setText("");
        jPasswordField1.setText("");
        jTextFieldNombre.setText("");
        jTextFieldApellido.setText("");
        jTextFieldEmail.setText("");
        jToggleButtonActividad.setSelected(false);
        jToggleButtonActividad.setText("Inactivo");
//        jButtonEliminarPaciente.setEnabled(false);
//        jButtonModificarPaciente.setEnabled(false);

        jLabelErrorMsg.setText(" ");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNSS = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListPacientes = new javax.swing.JList();
        jButtonGuardarPaciente = new javax.swing.JButton();
        jButtonModificarPaciente = new javax.swing.JButton();
        jButtonEliminarPaciente = new javax.swing.JButton();
        jToggleButtonActividad = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelErrorMsg = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Pacientes");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pacientes"));

        jLabel1.setText("Nombre:");

        jLabel2.setText("Apellido:");

        jLabel3.setText("Email:");

        jLabel4.setText("NSS:");

        jScrollPane1.setViewportView(jListPacientes);

        jButtonGuardarPaciente.setText("Crear");
        jButtonGuardarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarPacienteActionPerformed(evt);
            }
        });

        jButtonModificarPaciente.setText("Actualizar");
        jButtonModificarPaciente.setEnabled(false);
        jButtonModificarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarPacienteActionPerformed(evt);
            }
        });

        jButtonEliminarPaciente.setText("Eliminar");
        jButtonEliminarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarPacienteActionPerformed(evt);
            }
        });

        jToggleButtonActividad.setText("Inactivo");
        jToggleButtonActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonActividadActionPerformed(evt);
            }
        });

        jLabel5.setText("Actividad:");

        jLabel6.setText("Password:");

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelErrorMsg.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelErrorMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonGuardarPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonModificarPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(jButtonEliminarPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNSS)
                            .addComponent(jTextFieldNombre)
                            .addComponent(jTextFieldEmail)
                            .addComponent(jTextFieldApellido)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButtonActividad))
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldNSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonActividad)
                    .addComponent(jLabel5)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jLabelErrorMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonGuardarPaciente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonModificarPaciente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEliminarPaciente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(0, 56, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarPacienteActionPerformed
        String nss = jTextFieldNSS.getText();
        String password = new String(jPasswordField1.getPassword());
        String firstName = jTextFieldNombre.getText();
        String lastName = jTextFieldApellido.getText();
        String address = jTextFieldEmail.getText();
        boolean isActive = jToggleButtonActividad.isSelected();

        if (nss != null
                && firstName != null
                && lastName != null
                && address != null) {

            if (!nss.isEmpty()
                    && !firstName.isEmpty()
                    && !lastName.isEmpty()
                    && !address.isEmpty()
                    && !password.isEmpty()) {

                Validator val = Validator.getInstance();
                
                if (existeNSS(nss)) {
                    JOptionPane.showMessageDialog(null, "Verifica el NSS...", "Error", JOptionPane.ERROR_MESSAGE);
//                    jLabelErrorMsg.setText("El Email debe de tener solamente un @, y no puede estar al final.");
//                    jLabelErrorMsg.setForeground(Color.red);
                    return;
                }
                
                if(!val.isValidNss(nss)){
                    jLabelErrorMsg.setText("El NSS debe tener 11 dígitos y opcionalmente un guión.");
                    jLabelErrorMsg.setForeground(Color.red);
                    return;
                }
                
                if(!val.isValidFirstName(firstName)){
                    jLabelErrorMsg.setText("El nombre debe contener más de 2 caracteres y empezar con una mayúscula.");
                    jLabelErrorMsg.setForeground(Color.red);
                    return;
                }
                
                if(!val.isValidLastName(lastName)){
                    jLabelErrorMsg.setText("El apellido debe contener más de 2 caracteres y empezar con mayúscula.");
                    jLabelErrorMsg.setForeground(Color.red);
                    return;
                }

//                if (!esValidoElEmail(address)) {
//                    jLabelErrorMsg.setText("El Email debe de tener solamente un @, y no puede estar al final.");
//                    jLabelErrorMsg.setForeground(Color.red);
//                    return;
//                }
                
                if(!val.isValidEmail(address)){
                    jLabelErrorMsg.setText("El e-mail debe tener el siguiente formato 'correo@ejemplo.com'");
                    jLabelErrorMsg.setForeground(Color.red);
                    return;
                }
                
                if(!val.isValidPassword(password)){
                    jLabelErrorMsg.setText("La contraseña debe combinar mayúsculas, minúsculas y números.");
                    if(password.length() < 8)
                        jLabelErrorMsg.setText("La contraseña debe tener mínimo 8 caracteres.");
                    jLabelErrorMsg.setForeground(Color.red);
                    return;
                }

//                if (!esValidoNSS(nss)) {
//                    jLabelErrorMsg.setText("* El NSS debe tener solamente 11 digitos.");
//                    jLabelErrorMsg.setForeground(Color.red);
//                    return;
//                }

                Patient patient = new Patient(nss, password, firstName, lastName, address, isActive);
                ConectorPatientManager conectorPatient = ConectorPatientManager.getInstance();
                String saveNewPatient = conectorPatient.saveNewPatient(patient);

                if (saveNewPatient != null) {
                    JOptionPane.showMessageDialog(null, "El paciente fue creado exitosamente. ", "Paciente", JOptionPane.INFORMATION_MESSAGE);
                    limpiarCampos();
                    actualizarListaPacientes();
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo crear el Paciente...", "Error", JOptionPane.ERROR_MESSAGE);
                }

            } else {
                jLabelErrorMsg.setText("* Todo Campo debe de tener un dato.");
                jLabelErrorMsg.setForeground(Color.red);
            }
        } else {
            jLabelErrorMsg.setText("* Todo Campo debe de tener un dato.");
            jLabelErrorMsg.setForeground(Color.red);
        }
    }//GEN-LAST:event_jButtonGuardarPacienteActionPerformed

    private void jButtonModificarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarPacienteActionPerformed
        String nss = jTextFieldNSS.getText();

//        System.out.println(selectedPatient.getPassword());
        String password = new String(jPasswordField1.getPassword());
        if (password.isEmpty()) {
            password = selectedPatient.getPassword();
        }

        String firstName = jTextFieldNombre.getText();
        String lastName = jTextFieldApellido.getText();
        String address = jTextFieldEmail.getText();
        boolean isActive = jToggleButtonActividad.isSelected();

        if (nss != null
                && firstName != null
                && lastName != null
                && address != null) {

            if (!nss.isEmpty()
                    && !firstName.isEmpty()
                    && !lastName.isEmpty()
                    && !address.isEmpty()
                    && !password.isEmpty()) {

                Patient p = new Patient(selectedPatient.getNss(), password, firstName, lastName, address, isActive);
                p.setDoctorUsername(selectedPatient.getDoctorUsername());
                ConectorServicio servidor = ConectorServicio.getInstance();
                servidor.updatePatient(p);
                //TODO

                limpiarCampos();
                actualizarListaPacientes();
            } else {
                jLabelErrorMsg.setText("* Todo Campo debe de tener un dato.");
                jLabelErrorMsg.setForeground(Color.red);
            }
        } else {
            jLabelErrorMsg.setText("* Todo Campo debe de tener un dato.");
            jLabelErrorMsg.setForeground(Color.red);
        }
    }//GEN-LAST:event_jButtonModificarPacienteActionPerformed

    private void jButtonEliminarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarPacienteActionPerformed
        DefaultListModel modelo = (DefaultListModel) jListPacientes.getModel();
        int indice = jListPacientes.getSelectedIndex();
        if (indice != -1) {
            Patient cSel = (Patient) modelo.getElementAt(indice);
            ConectorServicio servidor = ConectorServicio.getInstance();
            servidor.eliminarPatient(cSel.getNss());

            //del modelo quitar paciente 
            modelo.remove(indice);

//            jButtonEliminarPaciente.setEnabled(false);
//            jButtonModificarPaciente.setEnabled(false);
            limpiarCampos();
            actualizarListaPacientes();
        }
    }//GEN-LAST:event_jButtonEliminarPacienteActionPerformed

    private void jToggleButtonActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonActividadActionPerformed
        if (jToggleButtonActividad.isSelected()) {
            jToggleButtonActividad.setText("Activo");
        } else {
            jToggleButtonActividad.setText("Inactivo");
        }
    }//GEN-LAST:event_jToggleButtonActividadActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private class ManejadorListaPacientes implements ListSelectionListener {

        @Override
        public void valueChanged(ListSelectionEvent e) {
            if (e.getValueIsAdjusting() == false) {
                int indice = jListPacientes.getSelectedIndex();
                if (indice == -1) {
//                    jButtonEliminarPaciente.setEnabled(false);
//                    jButtonModificarPaciente.setEnabled(false);
                } else {
//                    jButtonEliminarPaciente.setEnabled(true);
//                    jButtonModificarPaciente.setEnabled(true);

                    ListModel modelo = jListPacientes.getModel();
                    Patient cSel = (Patient) modelo.getElementAt(indice);
                    selectedPatient = cSel;

                    jTextFieldNombre.setText(cSel.getFirstName());
                    jTextFieldApellido.setText(cSel.getLastName());
                    jTextFieldEmail.setText(cSel.getAddress());
                    jTextFieldNSS.setText(cSel.getNss());
                    jPasswordField1.setText(cSel.getPassword());
//                    System.out.println(cSel.getPassword());

                    if (cSel.getIsActive()) {
                        jToggleButtonActividad.setSelected(true);
                        jToggleButtonActividad.setText("Activo");
                    } else {
                        jToggleButtonActividad.setSelected(false);
                        jToggleButtonActividad.setText("Inactivo");
                    }
                }
            }
        }
    }

    private boolean existeNSS(String un) {
        ListModel modelo = jListPacientes.getModel();
        for (int i = 0; i < modelo.getSize(); i++) {
            Patient d = (Patient) modelo.getElementAt(i);
            if (d.getNss().equalsIgnoreCase(un)) {
                return true;
            }
        }
        return false;
    }

    private boolean esValidoElEmail(String e) {
        int coutarrova = 0;
        for (int i = 0; i < e.length(); i++) {
            if (e.charAt(i) == '@') {
                coutarrova++;
            }
        }
        if (coutarrova == 1) {
            return true;
        }
        return false;
    }

    private boolean esValidoNSS(String ns) {
        if (ns.length() >= 11) {
            return true;
        }
        return false;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEliminarPaciente;
    private javax.swing.JButton jButtonGuardarPaciente;
    private javax.swing.JButton jButtonModificarPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelErrorMsg;
    private javax.swing.JList jListPacientes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNSS;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JToggleButton jToggleButtonActividad;
    // End of variables declaration//GEN-END:variables
}
